version: "3"
services:
  accounts:
    build: ./accounts
    env_file:
    - .env
  backend:
    build: ./backend
    ports:
      - "3000:${BACKEND_SERVER_PORT}"
    environment:
      - ACCOUNTS_ADDRESS=accounts:${ACCOUNTS_SERVER_PORT}
    env_file:
    - .env
    volumes:
      - ./shared:/shared
