version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:${ACCOUNTS_SERVER_PORT}"
    environment:
      - ACCOUNTS_ADDRESS=accounts:3001
    env_file:
    - .env
    volumes:
      - ./shared:/shared
  accounts:
    build: ./accounts
    ports:
     - "3001:${ACCOUNTS_SERVER_PORT}"
    env_file:
    - .env
