// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reports/reports.proto

/*
Package reports is a generated protocol buffer package.

It is generated from these files:
	reports/reports.proto

It has these top-level messages:
	Empty
	AccountID
	HabitsReport
	HabitsUserReport
	TasksReport
	TasksUserReport
*/
package reports

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import habits "pb/habits"
import tasks "pb/tasks"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AccountID struct {
	// Unique account id in the Task Manager system.
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountID) Reset()                    { *m = AccountID{} }
func (m *AccountID) String() string            { return proto.CompactTextString(m) }
func (*AccountID) ProtoMessage()               {}
func (*AccountID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HabitsReport struct {
	BlueCount   int64         `protobuf:"varint,1,opt,name=blue_count,json=blueCount" json:"blue_count,omitempty"`
	GreenCount  int64         `protobuf:"varint,2,opt,name=green_count,json=greenCount" json:"green_count,omitempty"`
	YellowCount int64         `protobuf:"varint,3,opt,name=yellow_count,json=yellowCount" json:"yellow_count,omitempty"`
	OrangeCount int64         `protobuf:"varint,4,opt,name=orange_count,json=orangeCount" json:"orange_count,omitempty"`
	RedCount    int64         `protobuf:"varint,5,opt,name=red_count,json=redCount" json:"red_count,omitempty"`
	Worst       *habits.Habit `protobuf:"bytes,6,opt,name=worst" json:"worst,omitempty"`
	Best        *habits.Habit `protobuf:"bytes,7,opt,name=best" json:"best,omitempty"`
}

func (m *HabitsReport) Reset()                    { *m = HabitsReport{} }
func (m *HabitsReport) String() string            { return proto.CompactTextString(m) }
func (*HabitsReport) ProtoMessage()               {}
func (*HabitsReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HabitsReport) GetBlueCount() int64 {
	if m != nil {
		return m.BlueCount
	}
	return 0
}

func (m *HabitsReport) GetGreenCount() int64 {
	if m != nil {
		return m.GreenCount
	}
	return 0
}

func (m *HabitsReport) GetYellowCount() int64 {
	if m != nil {
		return m.YellowCount
	}
	return 0
}

func (m *HabitsReport) GetOrangeCount() int64 {
	if m != nil {
		return m.OrangeCount
	}
	return 0
}

func (m *HabitsReport) GetRedCount() int64 {
	if m != nil {
		return m.RedCount
	}
	return 0
}

func (m *HabitsReport) GetWorst() *habits.Habit {
	if m != nil {
		return m.Worst
	}
	return nil
}

func (m *HabitsReport) GetBest() *habits.Habit {
	if m != nil {
		return m.Best
	}
	return nil
}

type HabitsUserReport struct {
	GoodHabits []*habits.Habit `protobuf:"bytes,1,rep,name=good_habits,json=goodHabits" json:"good_habits,omitempty"`
	BadHabits  []*habits.Habit `protobuf:"bytes,2,rep,name=bad_habits,json=badHabits" json:"bad_habits,omitempty"`
}

func (m *HabitsUserReport) Reset()                    { *m = HabitsUserReport{} }
func (m *HabitsUserReport) String() string            { return proto.CompactTextString(m) }
func (*HabitsUserReport) ProtoMessage()               {}
func (*HabitsUserReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HabitsUserReport) GetGoodHabits() []*habits.Habit {
	if m != nil {
		return m.GoodHabits
	}
	return nil
}

func (m *HabitsUserReport) GetBadHabits() []*habits.Habit {
	if m != nil {
		return m.BadHabits
	}
	return nil
}

type TasksReport struct {
	Delayed  []*tasks.Task `protobuf:"bytes,1,rep,name=delayed" json:"delayed,omitempty"`
	DueToday []*tasks.Task `protobuf:"bytes,2,rep,name=dueToday" json:"dueToday,omitempty"`
}

func (m *TasksReport) Reset()                    { *m = TasksReport{} }
func (m *TasksReport) String() string            { return proto.CompactTextString(m) }
func (*TasksReport) ProtoMessage()               {}
func (*TasksReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TasksReport) GetDelayed() []*tasks.Task {
	if m != nil {
		return m.Delayed
	}
	return nil
}

func (m *TasksReport) GetDueToday() []*tasks.Task {
	if m != nil {
		return m.DueToday
	}
	return nil
}

type TasksUserReport struct {
	CompletedTasks *TasksUserReport_CompletedTasks `protobuf:"bytes,1,opt,name=completed_tasks,json=completedTasks" json:"completed_tasks,omitempty"`
	AvailableTasks *TasksUserReport_AvailableTasks `protobuf:"bytes,2,opt,name=available_tasks,json=availableTasks" json:"available_tasks,omitempty"`
}

func (m *TasksUserReport) Reset()                    { *m = TasksUserReport{} }
func (m *TasksUserReport) String() string            { return proto.CompactTextString(m) }
func (*TasksUserReport) ProtoMessage()               {}
func (*TasksUserReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TasksUserReport) GetCompletedTasks() *TasksUserReport_CompletedTasks {
	if m != nil {
		return m.CompletedTasks
	}
	return nil
}

func (m *TasksUserReport) GetAvailableTasks() *TasksUserReport_AvailableTasks {
	if m != nil {
		return m.AvailableTasks
	}
	return nil
}

type TasksUserReport_CompletedTasks struct {
	OnTime     int64 `protobuf:"varint,1,opt,name=onTime" json:"onTime,omitempty"`
	BeforeTime int64 `protobuf:"varint,2,opt,name=beforeTime" json:"beforeTime,omitempty"`
	Delayed    int64 `protobuf:"varint,3,opt,name=delayed" json:"delayed,omitempty"`
}

func (m *TasksUserReport_CompletedTasks) Reset()         { *m = TasksUserReport_CompletedTasks{} }
func (m *TasksUserReport_CompletedTasks) String() string { return proto.CompactTextString(m) }
func (*TasksUserReport_CompletedTasks) ProtoMessage()    {}
func (*TasksUserReport_CompletedTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *TasksUserReport_CompletedTasks) GetOnTime() int64 {
	if m != nil {
		return m.OnTime
	}
	return 0
}

func (m *TasksUserReport_CompletedTasks) GetBeforeTime() int64 {
	if m != nil {
		return m.BeforeTime
	}
	return 0
}

func (m *TasksUserReport_CompletedTasks) GetDelayed() int64 {
	if m != nil {
		return m.Delayed
	}
	return 0
}

type TasksUserReport_AvailableTasks struct {
	Remaining int64 `protobuf:"varint,1,opt,name=remaining" json:"remaining,omitempty"`
	ForToday  int64 `protobuf:"varint,2,opt,name=forToday" json:"forToday,omitempty"`
	Delayed   int64 `protobuf:"varint,3,opt,name=delayed" json:"delayed,omitempty"`
}

func (m *TasksUserReport_AvailableTasks) Reset()         { *m = TasksUserReport_AvailableTasks{} }
func (m *TasksUserReport_AvailableTasks) String() string { return proto.CompactTextString(m) }
func (*TasksUserReport_AvailableTasks) ProtoMessage()    {}
func (*TasksUserReport_AvailableTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 1}
}

func (m *TasksUserReport_AvailableTasks) GetRemaining() int64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *TasksUserReport_AvailableTasks) GetForToday() int64 {
	if m != nil {
		return m.ForToday
	}
	return 0
}

func (m *TasksUserReport_AvailableTasks) GetDelayed() int64 {
	if m != nil {
		return m.Delayed
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "reports.Empty")
	proto.RegisterType((*AccountID)(nil), "reports.AccountID")
	proto.RegisterType((*HabitsReport)(nil), "reports.HabitsReport")
	proto.RegisterType((*HabitsUserReport)(nil), "reports.HabitsUserReport")
	proto.RegisterType((*TasksReport)(nil), "reports.TasksReport")
	proto.RegisterType((*TasksUserReport)(nil), "reports.TasksUserReport")
	proto.RegisterType((*TasksUserReport_CompletedTasks)(nil), "reports.TasksUserReport.CompletedTasks")
	proto.RegisterType((*TasksUserReport_AvailableTasks)(nil), "reports.TasksUserReport.AvailableTasks")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReportsService service

type ReportsServiceClient interface {
	GetHabitsReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HabitsReport, error)
	GetHabitsUserReport(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*HabitsUserReport, error)
	GetTasksReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksReport, error)
	GetTasksUserReport(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*TasksUserReport, error)
}

type reportsServiceClient struct {
	cc *grpc.ClientConn
}

func NewReportsServiceClient(cc *grpc.ClientConn) ReportsServiceClient {
	return &reportsServiceClient{cc}
}

func (c *reportsServiceClient) GetHabitsReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HabitsReport, error) {
	out := new(HabitsReport)
	err := grpc.Invoke(ctx, "/reports.ReportsService/GetHabitsReport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsServiceClient) GetHabitsUserReport(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*HabitsUserReport, error) {
	out := new(HabitsUserReport)
	err := grpc.Invoke(ctx, "/reports.ReportsService/GetHabitsUserReport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsServiceClient) GetTasksReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TasksReport, error) {
	out := new(TasksReport)
	err := grpc.Invoke(ctx, "/reports.ReportsService/GetTasksReport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsServiceClient) GetTasksUserReport(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*TasksUserReport, error) {
	out := new(TasksUserReport)
	err := grpc.Invoke(ctx, "/reports.ReportsService/GetTasksUserReport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReportsService service

type ReportsServiceServer interface {
	GetHabitsReport(context.Context, *Empty) (*HabitsReport, error)
	GetHabitsUserReport(context.Context, *AccountID) (*HabitsUserReport, error)
	GetTasksReport(context.Context, *Empty) (*TasksReport, error)
	GetTasksUserReport(context.Context, *AccountID) (*TasksUserReport, error)
}

func RegisterReportsServiceServer(s *grpc.Server, srv ReportsServiceServer) {
	s.RegisterService(&_ReportsService_serviceDesc, srv)
}

func _ReportsService_GetHabitsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).GetHabitsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reports.ReportsService/GetHabitsReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).GetHabitsReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportsService_GetHabitsUserReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).GetHabitsUserReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reports.ReportsService/GetHabitsUserReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).GetHabitsUserReport(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportsService_GetTasksReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).GetTasksReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reports.ReportsService/GetTasksReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).GetTasksReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportsService_GetTasksUserReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).GetTasksUserReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reports.ReportsService/GetTasksUserReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).GetTasksUserReport(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reports.ReportsService",
	HandlerType: (*ReportsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHabitsReport",
			Handler:    _ReportsService_GetHabitsReport_Handler,
		},
		{
			MethodName: "GetHabitsUserReport",
			Handler:    _ReportsService_GetHabitsUserReport_Handler,
		},
		{
			MethodName: "GetTasksReport",
			Handler:    _ReportsService_GetTasksReport_Handler,
		},
		{
			MethodName: "GetTasksUserReport",
			Handler:    _ReportsService_GetTasksUserReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reports/reports.proto",
}

func init() { proto.RegisterFile("reports/reports.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x94, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0x1b, 0xa7, 0x79, 0x1b, 0xe7, 0x71, 0x1e, 0xb6, 0x14, 0x19, 0x97, 0x97, 0xd4, 0x08,
	0xb5, 0x07, 0xe4, 0x48, 0xe1, 0x82, 0xb8, 0x95, 0x16, 0x0a, 0x37, 0x14, 0xc2, 0x05, 0x09, 0x45,
	0xeb, 0xec, 0x34, 0x58, 0x38, 0x5e, 0x6b, 0xbd, 0x69, 0x95, 0xef, 0xc1, 0x97, 0xe5, 0x04, 0xf2,
	0xbe, 0x38, 0x71, 0x68, 0xd5, 0x4b, 0xa2, 0x99, 0xff, 0x6f, 0x66, 0x76, 0x76, 0x66, 0x0d, 0x87,
	0x02, 0x73, 0x2e, 0x64, 0x31, 0x32, 0xff, 0x51, 0x2e, 0xb8, 0xe4, 0xa4, 0x63, 0xcc, 0xe0, 0xe0,
	0x07, 0x8d, 0x13, 0x59, 0x8c, 0xf4, 0x9f, 0x56, 0x83, 0x07, 0x92, 0x16, 0x3f, 0x8b, 0x91, 0xfa,
	0xd5, 0xae, 0xb0, 0x03, 0xad, 0xf7, 0xcb, 0x5c, 0xae, 0xc3, 0x23, 0xe8, 0x9d, 0xcd, 0xe7, 0x7c,
	0x95, 0xc9, 0x4f, 0x17, 0xc4, 0x03, 0x27, 0x61, 0x7e, 0x63, 0xd8, 0x38, 0x6d, 0x4e, 0x9c, 0x84,
	0x85, 0xbf, 0x1b, 0xd0, 0xff, 0xa8, 0x32, 0x4d, 0x54, 0x7e, 0xf2, 0x14, 0x20, 0x4e, 0x57, 0x38,
	0x53, 0x01, 0x06, 0xec, 0x95, 0x9e, 0xf3, 0xd2, 0x41, 0x9e, 0x83, 0xbb, 0x10, 0x88, 0x99, 0xd1,
	0x1d, 0xa5, 0x83, 0x72, 0x69, 0xe0, 0x18, 0xfa, 0x6b, 0x4c, 0x53, 0x7e, 0x63, 0x88, 0xa6, 0x22,
	0x5c, 0xed, 0xab, 0x10, 0x2e, 0x68, 0xb6, 0xb0, 0x45, 0xf6, 0x35, 0xa2, 0x7d, 0x1a, 0x39, 0x82,
	0x9e, 0x40, 0x66, 0xf4, 0x96, 0xd2, 0xbb, 0x02, 0x99, 0x16, 0x5f, 0x40, 0xeb, 0x86, 0x8b, 0x42,
	0xfa, 0xed, 0x61, 0xe3, 0xd4, 0x1d, 0xff, 0x17, 0x99, 0xab, 0x50, 0x7d, 0x4c, 0xb4, 0x46, 0x8e,
	0x61, 0x3f, 0xc6, 0x42, 0xfa, 0x9d, 0xdb, 0x18, 0x25, 0x85, 0x39, 0xfc, 0xaf, 0x5b, 0xff, 0x5a,
	0xa0, 0x30, 0xed, 0x47, 0xe0, 0x2e, 0x38, 0x67, 0x33, 0x8d, 0xfb, 0x8d, 0x61, 0xf3, 0xdf, 0x68,
	0x28, 0x09, 0x1d, 0x49, 0x5e, 0x01, 0xc4, 0xb4, 0xc2, 0x9d, 0xdb, 0xf0, 0x5e, 0x4c, 0x0d, 0x1d,
	0x7e, 0x07, 0x77, 0x5a, 0x8e, 0xc8, 0x14, 0x7b, 0x09, 0x1d, 0x86, 0x29, 0x5d, 0x23, 0x33, 0x85,
	0xdc, 0x48, 0x4f, 0xb0, 0x84, 0x26, 0x56, 0x23, 0x27, 0xd0, 0x65, 0x2b, 0x9c, 0x72, 0x46, 0xd7,
	0xa6, 0x42, 0x8d, 0xab, 0xc4, 0xf0, 0x8f, 0x03, 0x03, 0x95, 0x7f, 0xab, 0xa1, 0xcf, 0x30, 0x98,
	0xf3, 0x65, 0x9e, 0xa2, 0x44, 0x36, 0x53, 0x51, 0x6a, 0xa8, 0xee, 0xf8, 0x24, 0xb2, 0x0b, 0xb6,
	0x13, 0x12, 0x9d, 0x5b, 0x5e, 0x9f, 0xd5, 0x9b, 0xd7, 0xec, 0x32, 0x23, 0xbd, 0xa6, 0x49, 0x4a,
	0xe3, 0x14, 0x4d, 0x46, 0xe7, 0x9e, 0x8c, 0x67, 0x96, 0x37, 0x19, 0x69, 0xcd, 0x0e, 0x62, 0xf0,
	0xea, 0x35, 0xc9, 0x23, 0x68, 0xf3, 0x6c, 0x9a, 0x2c, 0xd1, 0x6c, 0xa0, 0xb1, 0xc8, 0x33, 0x80,
	0x18, 0xaf, 0xb8, 0x40, 0xa5, 0x99, 0xed, 0xdb, 0x78, 0x88, 0xbf, 0xb9, 0x51, 0xbd, 0x78, 0xd6,
	0x0c, 0x18, 0x78, 0xf5, 0x53, 0x90, 0x27, 0xe5, 0x8e, 0x2d, 0x69, 0x92, 0x25, 0xd9, 0xc2, 0x2e,
	0x7a, 0xe5, 0x20, 0x01, 0x74, 0xaf, 0xb8, 0xb0, 0x97, 0xae, 0x16, 0xd0, 0xda, 0x77, 0x57, 0x19,
	0xff, 0x72, 0xc0, 0xd3, 0x3d, 0x17, 0x5f, 0x50, 0x5c, 0x27, 0x73, 0x24, 0x6f, 0x61, 0x70, 0x89,
	0xb2, 0xf6, 0xc6, 0xbc, 0xea, 0xa2, 0xd4, 0x0b, 0x0d, 0x0e, 0x2b, 0x7b, 0x1b, 0x0b, 0xf7, 0xc8,
	0x07, 0x38, 0xa8, 0x62, 0xb7, 0x66, 0x4a, 0x2a, 0xbe, 0x7a, 0xd8, 0xc1, 0xe3, 0x9d, 0x1c, 0x1b,
	0x3c, 0xdc, 0x23, 0x6f, 0xc0, 0xbb, 0x44, 0xb9, 0xbd, 0x7a, 0xbb, 0x47, 0x78, 0x58, 0x9f, 0x5d,
	0x15, 0x79, 0x01, 0xc4, 0x46, 0xde, 0x73, 0x00, 0xff, 0xae, 0xe9, 0x87, 0x7b, 0xef, 0xfa, 0xdf,
	0x20, 0x8f, 0xed, 0x07, 0x2d, 0x6e, 0xab, 0x0f, 0xd4, 0xeb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x41, 0x97, 0xaf, 0xd6, 0xea, 0x04, 0x00, 0x00,
}
